### ISSUE TITLE
Il manque de la documentation

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-doctypes#19]
Il manque la documentation pour les doctypes suivant :

- [ io.cozy.accounts](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.accounts.md)
- [io.cozy.apps](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.apps.md)
- [io.cozy.konnectors](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.konnectors.md)
- [io.cozy.settings](https://github.com/cozy/cozy-doctypes/blob/master/docs/io.cozy.settings.md)

**Comment by kosssi** [comment]
@CPatchane, @gregorylegarec, @Narkfr et @poupotte C'est dommage j'aurai voulu voir comment chez les platformers vous faisiez vos liens entre les `io.cozy.konnectors` et `io.cozy.accounts`.

Si vous pouvez ajouter la documentation pour que l'on soit cohérent entre nous c'est top.

**Comment by gregorylegarec** [comment]
@kosssi Via les triggers, ce sont les fameux triggers "v2" https://paper.dropbox.com/doc/Point-connecteurs-5xFUOLivp8s33826niQLN

**Comment by gregorylegarec** [comment]
https://github.com/cozy/cozy-doctypes/pull/28
