### ISSUE TITLE
Exemple pour chaque doctypes

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-doctypes#34]
En relisant la documentation des doctypes bancaire je me suis rendu compte que l'on n'affichait pas d'exemple ce qui peut poser un problème de compréhension.

Je serai pour que l'on mette un exemple pour chaque doctype.

Voici ce que ça donnerai pour un compte en banque:

```
{
  "label": "Livret A Isabelle",
  "institutionLabel": "La Banque Postale",
  "number": "123123123",
  "balance": 11635.12,
  "iban": "FR1420041010050500013M02606"
  "type": "Savings"
}
``` 

Vous en pensez quoi ?

**Comment by GoOz** [comment]
Explicit always better than implicit amha.

**Comment by ptbrowne** [comment]
Bonne idée, j'ai rajouté des exemples pour 

- [x] io.cozy.bank.operations
- [x] io.cozy.bank.accounts
- [x] io.cozy.bills

**Comment by ptbrowne** [comment]
Closing as duplicate of https://github.com/cozy/cozy-doctypes/issues/19
