### ISSUE TITLE
Date formats for DocTypes

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-doctypes#58]
Question : wich date format is the most relevant in DocTypes ?

In the bills docType, the specified format is : 
> "date: {date} - Date the bill was emitted, a string formated (what you get with a new Date().toString())"

But Date().toString() seems not relevant :

* [the ECMScript 2015](https://www.ecma-international.org/ecma-262/6.0/#sec-todatestring) specification says "Return **an implementation-dependent String value** that represents tv as a date and time in the current time zone using a convenient, human-readable form."

* [the ECMScript 2016 draft](https://tc39.github.io/ecma262/#sec-todatestring) specification says :
  > Let t be LocalTime(tv).
  Return the string-concatenation of DateString(t), the code unit 0x0020 (SPACE), TimeString(t), and TimeZoneString(tv). "

To help the decision : 
* In the meta data of docType, the expected format date is ISO8601 ([see here](https://github.com/cozy/cozy-doctypes#date-format))
* momentjs can be considered as the standard in JS and has also opted for ISO8601 by default : 
> moment().format();  // "2014-09-08T08:02:17-05:00" (ISO8601 format YYYY-MM-DDTHH:mm:ssZ)
> moment.utc().format();  // when in UTC mode, the default format is governed by moment.defaultFormatUtc which is in the format YYYY-MM-DDTHH:mm:ss[Z]. This returns Z as the offset, instead of +00:00. 

So, what is the most convenient date format in JS for DocTypes ? 
* `[Date().toISOString()](https://devdocs.io/javascript/global_objects/date/toisostring)` ?
* `[Date().toUTCString()](https://devdocs.io/javascript/global_objects/date/toutcstring)` ?
* other ?

**Comment by edas** [comment]
There is a mistake in the documentation. Let me fix that Monday.
`Date.toString()` is not an acceptable format.

The expected format is the ISO8601 one. 

--- 

Most if not all bills are created by connectors, which send a `Date`object to the old cozy-client-js, which in turn is natively converted in JSON when sent to CouchDB. Node `toJSON()` has the same output as `moment.utc().format()` with `moment.defaultFormatUtc`.

One should however not expect all dates to be in UTC by default and should be able to read ISO8601 dates with a timezone.
